_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: False
  WEIGHTS: "pretrained/mask_rcnn_mpvit_small_ms_3x.pth"
  MPVIT:
    NAME: "mpvit_small"
    DROP_PATH: 0.2
SOLVER:
  OPTIMIZER: "ADAMW"
  MAX_ITER: 300
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.0001
  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 50
  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 50
INPUT:
  CROP:
    ENABLED: True
    TYPE: "relative_range"
    SIZE: (0.9, 0.9)
AUG:
  DETR: True
OUTPUT_DIR: "output/mask_rcnn_mpvit_small_ms_3x"