_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: "https://dl.dropbox.com/s/3rk44pybi9jq9yq/mpvit_small_d2.pth"
  MPVIT:
    NAME: "mpvit_small"
    DROP_PATH: 0.2
INPUT:
  MIN_SIZE_TRAIN: (800,)
OUTPUT_DIR: "output/mask_rcnn_mpvit_small_ms_3x"