_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: "https://dl.dropbox.com/s/2khsfuj4zetjubw/mpvit_xsmall_d2.pth"
  MPVIT:
    NAME: "mpvit_xsmall"
    DROP_PATH: 0.1
INPUT:
  MIN_SIZE_TRAIN: (800,)
OUTPUT_DIR: "output/mask_rcnn_mpvit_xs_1x"