_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  MASK_ON: True
  WEIGHTS: "https://dl.dropbox.com/s/wiqpwiw35k7t6z7/mpvit_base_d2.pth"
  MPVIT:
    NAME: "mpvit_base"
    DROP_PATH: 0.4
INPUT:
  MIN_SIZE_TRAIN: (800,)
OUTPUT_DIR: "output/mask_rcnn_mpvit_base_1x"