_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "https://dl.dropbox.com/s/3rk44pybi9jq9yq/mpvit_small_d2.pth"
  MPVIT:
    NAME: "mpvit_small"
    DROP_PATH: 0.2
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
AUG:
  DETR: True
OUTPUT_DIR: "output/retinanet_mpvit_small_ms_3x"