_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "https://dl.dropbox.com/s/ys6fxsth2cn7j8w/mpvit_tiny_d2.pth"
  MPVIT:
    NAME: "mpvit_tiny"
    DROP_PATH: 0.1
INPUT:
  MIN_SIZE_TRAIN: (800,)
OUTPUT_DIR: "output/retinanet_mpvit_tiny_1x"