_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "https://dl.dropbox.com/s/2khsfuj4zetjubw/mpvit_xsmall_d2.pth"
  MPVIT:
    NAME: "mpvit_xsmall"
    DROP_PATH: 0.1
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
AUG:
  DETR: True
OUTPUT_DIR: "output/retinanet_mpvit_xs_ms_3x"