_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "pretrained/mpvit_tiny_d2.pth"
  MPVIT:
    NAME: "mpvit_tiny"
    DROP_PATH: 0.1
INPUT:
  MIN_SIZE_TRAIN: (800,)
SOLVER:
  OPTIMIZER: "ADAMW"
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.0001
  IMS_PER_BATCH: 2
OUTPUT_DIR: "output/retinanet_mpvit_tiny_1x"