_BASE_: "../Base-RetinaNet.yaml"
MODEL:
  WEIGHTS: "https://dl.dropbox.com/s/2khsfuj4zetjubw/mpvit_xsmall_d2.pth"
  MPVIT:
    NAME: "mpvit_xsmall"
    DROP_PATH: 0.1
INPUT:
  MIN_SIZE_TRAIN: (800,)
OUTPUT_DIR: "output/retinanet_mpvit_xs_1x"